#! /bin/bash
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias z='zellij -l welcome'
alias z1='zellij --session first-test --layout ~/.config/zellij/first_layout.kdl'
alias zs='zellij --layout ~/.config/zellij/simulator_layout.kdl'
alias za='zellij attach'
alias zl='zellij list-sessions'
alias lg='lazygit'
alias ld='lazydocker'

alias checkVPN='ping salfp1'
alias latex='docker run -v `pwd`:/tmp latex pdflatex'
alias e='emacs . &'
alias so='source ~/.bashrc'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias upup='update && upgrade'
alias clean_docker='docker system prune -af --volumes && docker rm -vf $(docker ps -aq) && docker rmi -f $(docker images -aq)'
alias V='~/SAL/bin/smb-dfs1.sh'
alias yazi='~/Github/yazi/target/release/yazi'
alias va='source .venv/bin/activate'
alias vd='deactivate'
alias vv='python3 -m venv .venv'
alias vu='python3 -m pip install -r requirements.txt'

eval "$(starship init bash)"
